#!/usr/bin/env node

var recast = require("recast"),
    jsesc = require("jsesc");

var input = [];

process.stdin
    .on("error", errored)
    .on("data", dataed)
    .on("end", ended);

function errored(error) {
  throw error;
}

function dataed(data) {
  input.push(data);
}

function ended() {
  var ast = recast.parse(Buffer.concat(input).toString("utf-8"));

  recast.visit(ast, {
    visitLiteral: function(path) {
      var node = path.value;
      if (typeof node.value === "string") { // A new String prevents Recast from re-escaping!
        node.value = new String(jsesc(node.value, {wrap: true, quotes: node.raw[0] === "'" ? "single" : "double"}));
      }
      this.traverse(path);
    }
  });

  process.stdout.write(recast.print(ast).code);
}
